
import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import '../models/product.dart';

class ProductService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseStorage _storage = FirebaseStorage.instance;

  // Get a stream of products
  Stream<List<Product>> getProducts() {
    return _firestore.collection('products').snapshots().map((snapshot) {
      return snapshot.docs.map((doc) {
        return Product.fromMap(doc.id, doc.data());
      }).toList();
    });
  }

  // Add a new product
  Future<void> addProduct(Product product, File image) async {
    final imageUrl = await _uploadImage(image);
    final newProduct = Product(
      id: '', // ID will be generated by Firestore
      name: product.name,
      price: product.price,
      imageUrl: imageUrl,
    );
    await _firestore.collection('products').add(newProduct.toMap());
  }

  // Update an existing product
  Future<void> updateProduct(Product product, File? image) async {
    String imageUrl = product.imageUrl;
    if (image != null) {
      imageUrl = await _uploadImage(image);
    }
    final updatedProduct = Product(
      id: product.id,
      name: product.name,
      price: product.price,
      imageUrl: imageUrl,
    );
    await _firestore.collection('products').doc(product.id).update(updatedProduct.toMap());
  }

  // Delete a product
  Future<void> deleteProduct(String productId) async {
    await _firestore.collection('products').doc(productId).delete();
  }

  // Upload an image and get the URL
  Future<String> _uploadImage(File image) async {
    final ref = _storage.ref().child('product_images/${DateTime.now().toIso8601String()}');
    await ref.putFile(image);
    return await ref.getDownloadURL();
  }
}
